service: passify-be
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage,'local'}
  region: eu-central-1
  memorySize: 1024
  timeout: 20

  environment:
    DB_DIALECT: postgres
    DB_URI: postgresql://localhost:5432
    DB_USERNAME: postgres
    DB_HOST: localhost
    DB_NAME: postgres
    DB_PASSWORD: 6363
    DB_PORT: 5432
    JWT_SECRET: daskjfsdavalruajk

custom:
  migrationsPath: "./src/migrations/"

functions:
  authHandler:
    handler: src/handler/authHandler.authHandler
    events:
      - http:
          path: /auth/{method}
          method: POST
          cors: true

plugins:
  - serverless-offline
  - serverless-sequelize-migrations
